### PR TITLE
Open external links in new tab

### LINKED ISSUE #2128: Web links open in the same browser tab
**Describe the bug**
When an applicant clicks on a link within a form, it opens in the same browser tab. It's an issue because it opens over the draft form the applicant was working on. To navigate back to the form, the applicant would need to select "back" on their web browser. The preferred experience would be to force any link within a form to open in a new tab. 

**To Reproduce**
1. Go to https://civiform.seattle.gov/programs/testing_genericprogram
2. Complete the form until you see a link (like in the attachment)
3. Click the link
4. See that it opens in the same browsers tab as the draft form

**Expected behavior**
Links should open in a new tab

**Screenshots**
[Links open in same browser tab.pdf](https://github.com/seattle-uat/civiform/files/8344933/Links.open.in.same.browser.tab.pdf)
Attached

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by gwendolyngoetz**
### Description
* Allows the link generator to make links open in the same tab or a new tab.
* Sets external links to open in new tab. 
* Adds an open in new tab icon for external links.
* Slightly increases the default font size of the static text component.

### Checklist
- [x] Created tests which fail without the change (if possible)

### Issue(s)
Fixes #2128

before-after

### CODE REVIEW

File: server/test/views/components/TextFormatterTest.java [hunk 1]
```diff
@@ -25,11 +26,48 @@ public void urlsRenderCorrectly() {
...
+  public void urlsRenderToOpenInNewTabCorrectly() {
+    ImmutableList<DomContent> content =
+        TextFormatter.createLinksAndEscapeText(
+            "hello google.com http://internet.website", TextFormatter.UrlOpenAction.NewTab);
+
+    assertThat(content).hasSize(4);
+    assertThat(content.get(0).render()).isEqualTo(new Text("hello ").render());
+    assertThat(content.get(1).render())
+        .isEqualTo(
+            "<a href=\"http://google.com/\" class=\"text-seattle-blue\" target=\"_blank\">google.com<svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"currentColor\" stroke=\"currentColor\" stroke-width=\"1%\" aria-hidden=\"true\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" class=\"flex-shrink-0 h-5 w-auto inline ml-1 align-text-top\"><path d=\"M19 19H5V5H12V3H5C3.89 3 3 3.9 3 5V19C3 20.1 3.89 21 5 21H19C20.1 21 21 20.1 21 19V12H19V19ZM14 3V5H17.59L7.76 14.83L9.17 16.24L19 6.41V10H21V3H14Z\"></path></svg></a>");
```
Comment (clouser2) [inline server/test/views/components/TextFormatterTest.java:39]: Up to you, but I'd consider a less strict assertion to avoid having to inline the svg content (which may change at some point).

Maybe we could assert that the content starts with everything through `<svg ` and then assert that the content ends with `</svg></a>`. I know we lose some fidelity in what's being asserted with that approach, so understand if you'd prefer to keep the full SVG content inlined.

Same for the assertion below.

File: server/app/views/applicant/ProgramIndexView.java [hunk 2]
```diff
@@ -29,6 +29,7 @@
 import services.program.ProgramDefinition;
 import views.BaseHtmlView;
 import views.HtmlBundle;
+import views.components.Icons;
```
Comment (clouser2) [inline server/app/views/applicant/ProgramIndexView.java:32]: Top-level comment: I'd consider adding before/after screenshots to the PR description. That'd make understanding the Tailwind style applications a bit easier.

**Review by clouser2 — APPROVED** [review]

File: server/test/views/components/TextFormatterTest.java (hunk 1 above)
Comment (gwendolyngoetz) [reply server/test/views/components/TextFormatterTest.java]: Good idea. Fixed

File: server/app/views/applicant/ProgramIndexView.java (hunk 2 above)
Comment (gwendolyngoetz) [reply server/app/views/applicant/ProgramIndexView.java:32]: Done :)

**Review by clouser2 — APPROVED** [review]

**Review by bion — APPROVED** [review]
