### PR TITLE
Make sure static questions are always shown

### LINKED ISSUE #1555: Static question type not visible on published forms
**Describe the bug**
The static question type does not display on the published forms. I am able to create a static question (i.e. with our Privacy Statement on it) and publish it to a program. But when residents/TIs open the form, they don't see any text. The form "skips" over the static text and goes straight to the next section of questions.

**To Reproduce**
1. Create a static question (i.e. text from the privacy statement)
2. Drag the question onto a form (in Admin view)
3. Publish form (in Admin view)
4. Login as a user/resident and start form (i.e. the Seattle Preschool Program)
5. Static text will not appear

**Expected behavior**
I would expect the static text to appear.

**Screenshots**
Attached

**Desktop (please complete the following information):**
Chrome
[Static Question Issue.docx](https://github.com/seattle-uat/civiform/files/6851715/Static.Question.Issue.docx)

### PR DESCRIPTION
**Pull request by lindsayzad**
### Description
Change the logic to return blocks so that if a block contains a static question it is always shown to the user.  This is regardless of whether there are other questions on the block that have already been answered and would not have been shown again beforehand.  See issue #1555 for more detail.

Includes:
 - unit tests for all scenarios that could arise
 - Changed logic
 - browser test for a static question block to make sure it is shown to the user.

Fixes #1555

Peer programmed with ettengererin and dkatzz

### CODE REVIEW

File: browser-test/src/support/admin_questions.ts [hunk 1]
```diff
@@ -330,6 +330,29 @@ export class AdminQuestions {
...
+      questionText = 'static question text',
+      enumeratorName = AdminQuestions.DOES_NOT_REPEAT_OPTION) {
+      await this.gotoAdminQuestionsPage();
+      // Wait for dropdown event listener to be attached
+      await this.page.waitForLoadState('load');
+      await this.page.click('#create-question-button');
+
+      await this.page.click('#create-static-question');
+
+     await this.page.fill('label:has-text("Name")', questionName);
```
Comment (leonwong) [inline browser-test/src/support/admin_questions.ts:344]: nit - inconsistent indentation

File: browser-test/src/support/applicant_questions.ts [hunk 2]
```diff
@@ -116,4 +116,8 @@ export class ApplicantQuestions {
     expect(await this.page.innerHTML('head'))
       .toContain('<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">');
   }
+
+  async seeStaticQuestion(questionText: string){
+      expect(await this.page.textContent('html')).toContain(questionText);
```
Comment (leonwong) [inline browser-test/src/support/applicant_questions.ts:121]: nit - maybe a more specific selector for textContent if there's a stable container?

File: universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java [hunk 3]
```diff
@@ -68,7 +68,8 @@ public String getProgramTitle() {
           getBlocks(
               block ->
                   (!block.isCompleteWithoutErrors()
-                          || block.wasCompletedInProgram(programDefinition.id()))
+                          || block.wasCompletedInProgram(programDefinition.id())
+                          || block.containsStatic())
```
Comment (leonwong) [inline universal-application-tool-0.0.1/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java:72]: nit - consider adding a comment explaining the rationale for this behavior of static blocks since it might not be entirely obvious to future code maintainers.

**Review by leonwong — APPROVED** [review]
Looks good! Just a had a couple tiny non-blocking suggestions.
