### PR TITLE
Using Terraform Resource to generate ssh key

### LINKED ISSUE #2383: Terraform Deplouy: Failing b/c it cannot find the bastion.pub file
Try to run bin/setup and see it fails with a missing ssh/bastion.pub error

### PR DESCRIPTION
**Pull request by goldblatt**
### Description
Terraform deploys are failing due to not being able to find a file, there's a terraform resource that lets us create the initial key so we can use that here. note this is purely to make the azure terraform code happy as we prevent all ingres to the machine and then to access the bastion you have to manually add your own key to it via the scripts

### Checklist
- [ ] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

### Issue(s)
Fixes #2383

### CODE REVIEW

File: cloud/azure/bin/lib/azure.sh [hunk 1]
```diff
@@ -175,6 +175,7 @@ function azure::get_current_user_id() {
 #   3. scope name
 #######################################
 function azure::ensure_role_assignment() {
+  echo "creating role assignment for ${2}"
```
Comment (shanemc-goog) [inline cloud/azure/bin/lib/azure.sh:178]: Suggestion: capture ${2} into a named var for readability.

**Review by shanemc-goog — APPROVED** [review]
